MODEL:
  TYPE: resnet18
  NUM_CLASSES: 100
  OUTPUT_MID_LAYER: False
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: steps
  STEPS: [0,160] #[0, 30, 60, 90]
  LR_MULT: 0.1 #after step mutl 0.1
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  NESTEROV: False
TRAIN:
  DATASET: cifar100
  SPLIT: train
  BATCH_SIZE: 128
  IM_SIZE: 32
TEST:
  DATASET: cifar100
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .
LOG_PERIOD: 100
SAVE_EPOCH: []
